// Client-safe permissions constants
// This file should NOT import any server-only modules like database or auth

// Define all permissions in the system
export const PERMISSIONS = {
  // Property permissions
  PROPERTIES_VIEW: "properties:view",
  PROPERTIES_CREATE: "properties:create",
  PROPERTIES_EDIT: "properties:edit",
  PROPERTIES_DELETE: "properties:delete",
  
  // Tenant permissions
  TENANTS_VIEW: "tenants:view",
  TENANTS_CREATE: "tenants:create",
  TENANTS_EDIT: "tenants:edit",
  TENANTS_DELETE: "tenants:delete",
  
  // Lease permissions
  LEASES_VIEW: "leases:view",
  LEASES_CREATE: "leases:create",
  LEASES_EDIT: "leases:edit",
  LEASES_DELETE: "leases:delete",
  
  // Invoice permissions
  INVOICES_VIEW: "invoices:view",
  INVOICES_CREATE: "invoices:create",
  INVOICES_EDIT: "invoices:edit",
  INVOICES_DELETE: "invoices:delete",
  
  // Work Order permissions
  WORK_ORDERS_VIEW: "work_orders:view",
  WORK_ORDERS_CREATE: "work_orders:create",
  WORK_ORDERS_EDIT: "work_orders:edit",
  WORK_ORDERS_DELETE: "work_orders:delete",
  WORK_ORDERS_ASSIGN: "work_orders:assign",
  
  // Agent permissions
  AGENTS_VIEW: "agents:view",
  AGENTS_CONFIGURE: "agents:configure",
  AGENTS_APPROVE: "agents:approve",
  AGENTS_REJECT: "agents:reject",
  
  // Analytics permissions
  ANALYTICS_VIEW: "analytics:view",
  ANALYTICS_EXPORT: "analytics:export",
  
  // Settings permissions
  SETTINGS_VIEW: "settings:view",
  SETTINGS_EDIT: "settings:edit",
  
  // User management permissions
  USERS_VIEW: "users:view",
  USERS_CREATE: "users:create",
  USERS_EDIT: "users:edit",
  USERS_DELETE: "users:delete",
  
  // Equipment permissions
  EQUIPMENT_VIEW: "equipment:view",
  EQUIPMENT_CREATE: "equipment:create",
  EQUIPMENT_EDIT: "equipment:edit",
  EQUIPMENT_DELETE: "equipment:delete",
  
  // Vendor permissions
  VENDORS_VIEW: "vendors:view",
  VENDORS_CREATE: "vendors:create",
  VENDORS_EDIT: "vendors:edit",
  VENDORS_DELETE: "vendors:delete",
  
  // Compliance permissions
  COMPLIANCE_VIEW: "compliance:view",
  COMPLIANCE_CREATE: "compliance:create",
  COMPLIANCE_EDIT: "compliance:edit",
  COMPLIANCE_DELETE: "compliance:delete",
} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]

// Default role permission mappings
export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  super_admin: Object.values(PERMISSIONS),
  
  organization_admin: [
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.PROPERTIES_CREATE,
    PERMISSIONS.PROPERTIES_EDIT,
    PERMISSIONS.TENANTS_VIEW,
    PERMISSIONS.TENANTS_CREATE,
    PERMISSIONS.TENANTS_EDIT,
    PERMISSIONS.LEASES_VIEW,
    PERMISSIONS.LEASES_CREATE,
    PERMISSIONS.LEASES_EDIT,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_EDIT,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_CREATE,
    PERMISSIONS.WORK_ORDERS_EDIT,
    PERMISSIONS.WORK_ORDERS_ASSIGN,
    PERMISSIONS.AGENTS_VIEW,
    PERMISSIONS.AGENTS_CONFIGURE,
    PERMISSIONS.AGENTS_APPROVE,
    PERMISSIONS.AGENTS_REJECT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.EQUIPMENT_CREATE,
    PERMISSIONS.EQUIPMENT_EDIT,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.VENDORS_CREATE,
    PERMISSIONS.VENDORS_EDIT,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.COMPLIANCE_CREATE,
    PERMISSIONS.COMPLIANCE_EDIT,
  ],
  
  property_manager: [
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.TENANTS_VIEW,
    PERMISSIONS.TENANTS_CREATE,
    PERMISSIONS.TENANTS_EDIT,
    PERMISSIONS.LEASES_VIEW,
    PERMISSIONS.LEASES_CREATE,
    PERMISSIONS.LEASES_EDIT,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_CREATE,
    PERMISSIONS.WORK_ORDERS_EDIT,
    PERMISSIONS.WORK_ORDERS_ASSIGN,
    PERMISSIONS.AGENTS_VIEW,
    PERMISSIONS.AGENTS_APPROVE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.EQUIPMENT_EDIT,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
  ],
  
  accountant: [
    PERMISSIONS.TENANTS_VIEW,
    PERMISSIONS.LEASES_VIEW,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
  ],
  
  maintenance_staff: [
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_EDIT,
    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.EQUIPMENT_EDIT,
    PERMISSIONS.VENDORS_VIEW,
  ],
  
  tenant_user: [
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.WORK_ORDERS_CREATE,
    PERMISSIONS.INVOICES_VIEW,
  ],
  
  viewer: [
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.TENANTS_VIEW,
    PERMISSIONS.LEASES_VIEW,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.WORK_ORDERS_VIEW,
    PERMISSIONS.AGENTS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
  ],
}

